### ISSUE TITLE
Not optimizing constants near parameters

### ISSUE THREAD

**Issue by eugenca** [Thorium/Linq.Expression.Optimizer#16]
### Description

I used NCalc2 to parse string to Expression

### Repro steps

Console.WriteLine(expression);
Console.WriteLine(optimizedExpr);
this yields:

for expression "x+2+2+2"
initial: (((ctx.x + Convert(2, Double)) + Convert(2, Double)) + Convert(2, Double))
optimized: (((ctx.x + Convert(2, Double)) + Convert(2, Double)) + Convert(2, Double))
Should be: (ctx.x + Convert(6, Double))

for expression "x+(2+2+2)"
initial: (ctx.x + Convert(((2 + 2) + 2), Double))
optimized: (ctx.x + Convert(6, Double))
Should be: This is fine!

### Expected behavior

Both of them must be able to shorten expression

### Known workarounds

add parentheses

### Related information 

* Windows, webasm
* net.8

**Comment by eugenca** [comment]
also
for expression "x+(2+2+2)+(3+3+3)+(y*2%7)+(5*2%7)"
initial: ((((ctx.x + Convert(((2 + 2) + 2), Double)) + Convert(((3 + 3) + 3), Double)) + ((ctx.y * Convert(2, Double)) % Convert(7, Double))) + Convert(((5 * 2) % 7), Double))
optimized: ((((ctx.x + Convert(6, Double)) + Convert(9, Double)) + ((ctx.y * Convert(2, Double)) % Convert(7, Double))) + Convert(3, Double))

**Comment by eugenca** [comment]
Its the same, I tried too

**Comment by eugenca** [comment]
Actually you could use https://eugenca.github.io/wasm_projects/runge-kutta/
In developer console, I added output of initial and optimized
![image](https://github.com/Thorium/Linq.Expression.Optimizer/assets/5236164/af197836-5036-4d97-a27c-12482dd4f038)

**Comment by Thorium** [comment]
I think this Convert function came with .Net 8, at least I didn't seee that before. Can we expect it's side-effect free and "no-op" on which cases? Because `Convert(2.4, Int)+Convert(2.4, Int)+Convert(2.4, Int)` is not the same as `Convert(2.4+2.4+2.4, Int)`

**Comment by eugenca** [comment]
There are no Convert functions on the screenshots

**Comment by Thorium** [comment]
Putting the Converts aside:

2+2+2+x works well too.

The bottom of the issue is that Linq expression tree math, e.g. ExpressionType.Add is BinaryExpression of 2 parameters: left and right, so there is no array of additions. Thus the expression of a+b+c is either add(add(a, b), c) or add(a, add(b, c)) not add(a, b, c).

So your initial expression is (((x+2)+2)+2) as you can see from the initial issue. We only need a new rule that checks that 
a (parameter + constant) + constant = parameter + (constant + constant)
That's a fairly simple addition, I'll add it.

**Comment by Thorium** [comment]
Pushed 1.0.17 to Nuget, can you test if it helps?

I could imagine the core user-problem might be "I have an array of 3000 times +2 and I get stack-overflow with .NET Expressions", which Linq.Expression.Optimiser definitely should now help.

But the next question is how much math reductions should be generally supported? For example. if you feed a `(x + 4)*(x + 2)` should it come back with `x*x + 6x + 8`, when typically runtime caller will know the x and execute the equation faster than this Expression-AST-meta-level.

**Comment by eugenca** [comment]
Now it works, thank you!
expression: ((((ctx.x + 2) + 2) + 2) + 2)
dotnet.native.js:8 optimized expression: (ctx.x + 8)

If I'll encounter more issues, I'll post
