### ISSUE TITLE
1.0.19 causes FSharp.CoreFile not found exception

### ISSUE THREAD

**Issue by zyofeng** [Thorium/Linq.Expression.Optimizer#17]
### Description

Just recently updated to 1.0.19 and got the following runtime error, I noticed the library now relies on FSharp.Core 8 but the paket.template still references 6.0.7

Could not load file or assembly 'FSharp.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Reverting to previous version resolves the issue.

Probably need to build a new version now?

**Comment by Thorium** [comment]
Thanks for reporting this.
I'll de-list 1.0.19 and added a new version to Nuget 1.0.20, should be available soon.

**Comment by zyofeng** [comment]
All good, FSharp.CoreFile is netstandard 2.0 so it should be fine.
