### ISSUE TITLE
Unable to use NuGet this in a Microsoft.NETCore.App

### ISSUE THREAD

**Issue by StefH** [Thorium/Linq.Expression.Optimizer#3]
### Description

Unable to use this in a **Microsoft.NETCore.App** project.
### Repro steps

When adding Linq.Expression.Optimizer
to https://github.com/StefH/QueryInterceptor.Core/tree/master/test/QueryInterceptor.Core.ConsoleApp

And adding
`ExpressionOptimizer.visit;` to the Main(), you get error message like:
![opt-error-2](https://cloud.githubusercontent.com/assets/249938/19838140/317ddb7a-9ec9-11e6-8b1a-724a78c45ad3.png)

Also two references:
![opt-error-1](https://cloud.githubusercontent.com/assets/249938/19838139/2a2576a8-9ec9-11e6-8dbc-76cbfb337622.png)

The problem is that the `netcoreapp1.0` folder in the NuGet contains two dll's.
**Only** the _Linq.Expression.Optimizer.netcoreApp.dll_ should be there.

So the NuGet needs fixing.

BTW : I still think that my proposal to build the projects according to my PR (https://github.com/Thorium/Linq.Expression.Optimizer/pull/2) is still a better idea to structure the projects and generate the NuGets.

**Comment by Thorium** [comment]
Hmm. That PR built only Linq.Expression.Optimizer.netcore.dll but you say now that Linq.Expression.Optimizer.netcoreApp.dll is the correct one?

What is the difference between netcore and netcoreApp?

**Comment by StefH** [comment]
As far as I know, netcore is for .net core libraries. Which can be netstandard 1.0 to 1.6

Netcoreapp is for .net core apps (console app)

In my case I include your dll in a console app. And there are two dlls.


I think the solution is - refactor all projects according to my idea, or only provide the .net core dll, so no app dll

**Comment by StefH** [comment]
Any update? Or do you need help?

**Comment by Thorium** [comment]
Oh, I haven't looked this...

I kind of would like to stick with fake+paket scripts, but the should support .net core now.

**Comment by Thorium** [comment]
As far as I understand both are wrong and the target should be .NET standard. ([Described here](http://stackoverflow.com/a/40008152))

**Comment by Thorium** [comment]
Should be ok.
