### ISSUE TITLE
Please bring back support for .NETStandard 1.6

### ISSUE THREAD

**Issue by StefH** [Thorium/Linq.Expression.Optimizer#4]
### Description

Not able to use library in a .NETStandard,Version=v1.6 project.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a NETStandard Library in VS2017 and change the csproj to:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>

</Project>
```

### Expected behavior

Should work

### Actual behavior

Error message like:

> Package Linq.Expression.Optimizer 1.0.8 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Linq.Expression.Optimizer 1.0.8 supports:
>   - net35 (.NETFramework,Version=v3.5)
>   - net45 (.NETFramework,Version=v4.5)
>   - netcoreapp1.1 (.NETCoreApp,Version=v1.1)
> One or more packages are incompatible with .NETStandard,Version=v1.6.
> Package restore failed. Rolling back package changes for 'ClassLibrary1'.

Actually you can drop support for `NETCoreApp 1.1` because when your library is compatible with `NETStandard 1.6`, it's also compatible with `NETCoreApp 1.x`.

**Comment by Thorium** [comment]
I'll fix this tomorrow.

**Comment by Thorium** [comment]
Should work now, with 1.0.9.

**Comment by StefH** [comment]
I will try. Thanks.
