### ISSUE TITLE
Warning NU1603 Linq.Expression.Optimizer 1.0.9 depends on FSharp.Core (>= 4.2.0 && < 5.0.0) but FSharp.Core 4.2.0 was not found.

### ISSUE THREAD

**Issue by springy76** [Thorium/Linq.Expression.Optimizer#5]
### Description

After adding your NuGet package VS complains about unresolvable dependencies to a non existing FSharp.Core version.

### Repro steps

Add NuGet package to a new style C# project:

```
    <PackageReference Include="Linq.Expression.Optimizer" Version="1.0.9">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
```

### Expected behavior

No warnings or errors.

### Actual behavior

A soft warning NU1603:
> Linq.Expression.Optimizer 1.0.9 depends on FSharp.Core (>= 4.2.0 && < 5.0.0) but FSharp.Core 4.2.0 was not found. An approximate best match of FSharp.Core 4.2.1 was resolved.

### Known workarounds

Warning disappears when referencing a valid FSharp.Core version manually -- just adding `<NoWarn>NU1603</NoWarn>` to the `PackageReference` does not help.

```
    <PackageReference Include="FSharp.Core" Version="4.2.3">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
```

**Comment by Thorium** [comment]
It seems FSharp team has deleted NuGet package 4.2 and they shouldn't do that. >:-(
Ok, should be fixed now, Linq.Expression.Optimizer 1.0.11 is having more open dependency.
