### ISSUE TITLE
Inlined reference values break expression semantics

### ISSUE THREAD

**Issue by isc30** [Thorium/Linq.Expression.Optimizer#7]
### Description

Inlined reference values break expression semantics

### Repro steps

`e => !x.HasValue || x.Value < e.Something;`

### Expected behavior

`x.HasValue` gets evaluated first on the expression

### Actual behavior

It changes the order of the comparisons, resulting in a NullReferenceException

### Known workarounds

No

**Comment by Thorium** [comment]
It's not changed in such a simple case. I expect you have a lot more complex algebra. Do you know what is the rule that is breaking this?

As a workaround there is a mutable static array of `reductionMethods`, just exclude the rule that breaks your case.

**Comment by Thorium** [comment]
I don't know your use case, but this tool is more of pre-SQL-optimizer and usually SQL-engines do handle the null-checking in a way that you can compare `x.Value < 123` even if x is null, and also SQL-engines won't guarantee the execution order anyway: the database engine decides the best order to do the operations, and the operations won't have side-effects.

I guess another workaround would be having two LINQ Where (or Select) clauses, the first one to deal with the pre-condition null-checks and the next to handle the data. This optimizer shouldn't span over multiple methods or merge different operations (which would be nice feature btw).

**Comment by isc30** [comment]
Hi, thanks for the fast answer.
After some investigation it looks like the issue is somehow related to inlined constants.
Consider the following example:

    long? x = null;
    Expression<Func<Entity, bool>> predicate =
        e => !x.HasValue || x.Value < e.Amount;

Optimizer reduces this:
`e => !x.HasValue || x.Value < e.Amount;`

To this:
`e => !null.HasValue || null.Value < e.Amount;`

Which obviously trows `System.InvalidOperationException: Nullable object must have a value.` when using it with EntityFramework and `NullReferenceException` when compiled.

The proposed workaround looks good, but its sad to disable whole inlining because of this.

**Comment by Thorium** [comment]
Ok, I guess adding one null check wouldn't hurt so much...

Would you rather:
a) skip the inlining when a parameter is null
b) or check that if param is nullable and null, and called method is HasValue, replace with false?

The second option is not so reliable but it would have a benefit of optimizing your expression more, as the `!false || something` would be then replaced to true and non-null-cases would stay in the current form.

**Comment by Thorium** [comment]
The nullability problem should be fixed now, in Nuget version 1.0.12.
Any further optimizations, PRs are accepted. ;-)

**Comment by isc30** [comment]
great! thanks
